"""add_oauth_support_to_users

Revision ID: 7d3a637d0a30
Revises: 40439b022f4a
Create Date: 2025-09-11 16:08:11.538329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3a637d0a30'
down_revision = '40439b022f4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False)
    op.create_index('idx_users_provider', 'users', ['provider'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index('idx_users_provider', table_name='users')
    op.drop_index('idx_users_google_id', table_name='users')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
